#!/bin/bash
# VOICEVOX 初期値（聞きやすさ重視 / 初音短縮）
# 必要に応じて数値を調整してください
export VOICE_DEFAULT_SPEED=${VOICE_DEFAULT_SPEED:-1.28}
export VOICE_DEFAULT_VOLUME=${VOICE_DEFAULT_VOLUME:-1.10}
export VOICE_DEFAULT_PRE_S=${VOICE_DEFAULT_PRE_S:-0.03}
export VOICE_DEFAULT_POST_S=${VOICE_DEFAULT_POST_S:-0.04}
export VOICE_DEFAULT_PAUSE_SCALE=${VOICE_DEFAULT_PAUSE_SCALE:-0.65}


