# Grafana データソース設定

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
    secureJsonData: {}
    
  - name: OpenTelemetry
    type: prometheus
    access: proxy
    url: http://otel-collector:9464
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "10s"
      queryTimeout: "30s"
    secureJsonData: {}
    
  - name: Node Exporter
    type: prometheus
    access: proxy
    url: http://node-exporter:9100
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "30s"
    secureJsonData: {}
