name: PR Auto Labeler & Summary

"on":
  pull_request:
    types: [opened, synchronize]

jobs:
  label-and-summarize:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5

      - name: Auto label by paths
        uses: actions/labeler@v5
        with:
          sync-labels: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Summarize changes
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request
            const {owner, repo} = context.repo
            const files = await github.rest.pulls.listFiles({owner, repo, pull_number: pr.number})
            const counts = {}
            for (const f of files.data){
              const ext = (f.filename.split('.').pop() || 'other')
              counts[ext] = (counts[ext]||0)+1
            }
            const lines = Object.entries(counts).map(([k,v])=>`- ${k}: ${v} files`).join('\n')
            const body = `### Auto Summary\n${lines}`
            await github.rest.issues.createComment({owner, repo, issue_number: pr.number, body})

