name: spec-contract
on:
  push:
    branches: [ "**" ]
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install pytest pyyaml

      - name: Spec file exists
        run: test -f specs/speech_analysis_v1.yaml

      - name: Run tests
        run: pytest -q


