name: Test and Coverage

on:
  # 通知メール削減のため、mainブランチのみに制限
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # 手動実行も可能
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio pytest-cov
    
    - name: Run tests with coverage
      run: |
        if [ -d tests ]; then
          # 主要モジュールを対象にカバレッジ収集
          python -m pytest tests/ --cov=modules --cov=main_hybrid --cov-report=xml --cov-report=term
        else
          echo "tests/ が無いためスキップ"
          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><coverage></coverage>" > coverage.xml
        fi
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./coverage.xml
        fail_ci_if_error: false
        verbose: true
      continue-on-error: true